
[build-dependencies]

  [build-dependencies.tauri-build]
    features = []
    version = "1.3"

[dependencies]
  serde_json = "1.0"
  dirs = "5.0.1"
  futures = { version = "0.3.28", default-features = false }
  thiserror = "1.0.49"
  bytes = "1.5.0"

  [dependencies.tokio]
    features = ["process"]
    version = "1.32.0"

  [dependencies.reqwest]
    features = ["json", "blocking"]
    version = "0.11"

  [dependencies.serde]
    features = ["derive"]
    version = "1.0"

  [dependencies.tauri]
    features = ["updater", "system-tray", "process-exit", "dialog-all", "path-all", "shell-all"]
    version = "1.3"

[features]
  custom-protocol = ["tauri/custom-protocol"]

[package]
  authors = ["you"]
  description = "A Tauri App"
  edition = "2021"
  license = ""
  name = "prem-app"
  repository = ""
  version = "0.0.32"
